version: "3.9"
services:
  mysql:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 2705
    ports:
      - 3305:3306

  database:
    image: database
    container_name: database
    ports:
      - 8080:80

  backend:
    image: backend
    container_name: backend
    ports:
      - 8081:80

  frontend:
    image: frontend
    container_name: frontend
    ports:
      - 8082:80

    restart: unless-stopped
