version: "3.9"
services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 2705
    ports:
      - 3305:3306

  database:
    build:
      context: ./dataBase
    ports:
      - 8080:80

  backend:
    build:
      context: ./backEnd
    ports:
      - 8081:80

  frontend:
    build:
      context: ./frontend
    ports:
      - 8082:80

    restart: unless-stopped
